name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '0 9 * * 1' # Every Monday at 9 AM

jobs:
  e2e-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run E2E Tests
      run: npm run test:e2e
      env:
        BASE_URL: https://serpey-qa.vercel.app
    - name: Run API Tests
      run: npm run test:api
      env:
        BASE_URL: https://serpey-qa.vercel.app
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7